### ISSUE TITLE
Display Offline emails have broken image.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/display-monitoring-server#41]
![brokenimage](https://user-images.githubusercontent.com/8458926/55495697-1f357b00-5603-11e9-9834-2420f0339283.png)
Image in email sent to notify a user that their Display is offline is broken.

**Comment by tejohnso** [comment]
![offline](https://user-images.githubusercontent.com/1511535/55842386-43142780-5b01-11e9-9db9-c6427b9af27b.png)

corrected with [pr 42](https://github.com/Rise-Vision/display-monitoring-server/pull/42)
