### ISSUE TITLE
Display monitoring emails come from support@risevision.com

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/display-monitoring-server#63]
Display monitoring emails come from support@risevision.com causing hundreds of tickets anytime there is a display monitoring event. Emails should come from a no-reply address instead.

**Comment by alanclayton** [comment]
@tejohnso @btfrise per discussion at SoS. The problem is not that emails are sent from support@risevision.com. It is what is described on #64 

If you agree, I think this defect can be closed. Thanks
