### ISSUE TITLE
Display monitoring events cause display offline emails to go to users.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/display-monitoring-server#64]
We regularly have events that cause display monitoring to send emails out to users whose displays aren't really offline. This causes friction and confusion for the user, thinking that their displays are offline. In turn they create support tickets.

**Comment by tejohnso** [comment]
The plan for this is to add a circuit-breaker into the process so that if more than **X%** of displays are flagged for email alerts, the system will instead alert us in the alert room.
